// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRitRKu_o2aWAV9LEbSB-fGIhLPCrnxec',
    appId: '1:451561330042:web:6cba94215aba266e9d32c3',
    messagingSenderId: '451561330042',
    projectId: 'pizza-57061',
    authDomain: 'pizza-57061.firebaseapp.com',
    storageBucket: 'pizza-57061.firebasestorage.app',
    measurementId: 'G-5906JP18E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQULeTHBOWUpfDobnezefIUu_g26o91Jo',
    appId: '1:451561330042:android:2289b3e781d2c17e9d32c3',
    messagingSenderId: '451561330042',
    projectId: 'pizza-57061',
    storageBucket: 'pizza-57061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRblRxw7zuKzYNICH9fAY0k2YpcHovm3w',
    appId: '1:451561330042:ios:106a67b97a2deeb29d32c3',
    messagingSenderId: '451561330042',
    projectId: 'pizza-57061',
    storageBucket: 'pizza-57061.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRblRxw7zuKzYNICH9fAY0k2YpcHovm3w',
    appId: '1:451561330042:ios:106a67b97a2deeb29d32c3',
    messagingSenderId: '451561330042',
    projectId: 'pizza-57061',
    storageBucket: 'pizza-57061.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRitRKu_o2aWAV9LEbSB-fGIhLPCrnxec',
    appId: '1:451561330042:web:40bdf151599aeb619d32c3',
    messagingSenderId: '451561330042',
    projectId: 'pizza-57061',
    authDomain: 'pizza-57061.firebaseapp.com',
    storageBucket: 'pizza-57061.firebasestorage.app',
    measurementId: 'G-05HM8V9ZWX',
  );
}
